# Coding Temple's Data Analytics Program  
---
# Advanced Python 1 - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [48]:
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [2]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [60]:
import numpy as np
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility

myarray = np.random.randint(0,100, (5,3))

# Print out the array
print(myarray)

[[37 12 72]
 [ 9 75  5]
 [79 64 16]
 [ 1 76 71]
 [ 6 25 50]]


### 1.2 Solution - Run the following cell to check your answer.

In [ ]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [30]:
# height = [55, 120, 90, 100]
# weight = [170, 180, 190, 200]
# bmi = ((703 * weight) / (height**2))



NameError: name 'bmi' is not defined

### 1.3 Solution: Run the following cell to check your answer.

In [ ]:
# DO NOT EDIT THIS CELL
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'


### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [61]:
import numpy as np

def my_function(dtype=int, shape=(5,5)):
    if dtype == int:
        matrix_1 = np.random.randint(0,10, shape)
        print(f'\nFirst Matrix\n{matrix_1}')
        matrix_2 = np.random.randint(0,10, shape)
        print(f'\nSecond Matrix\n{matrix_2}')
    elif dtype == float:
        matrix_1 = np.random.uniform(0,10, shape)
        print(f'\nFirst Matrix\n{matrix_1}')
        matrix_2 = np.random.uniform(0,10, shape)
        print(f'\nSecond Matrix\n{matrix_2}')
my_function(dtype = int, shape=(3,3))


First Matrix
[[4 5 2]
 [4 2 4]
 [7 7 9]]

Second Matrix
[[1 7 0]
 [6 9 9]
 [7 6 9]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [100]:
# 1. Return the first row:
matrix = np.arange(0,25).reshape(5,5)
print(matrix)
print(f'\nThis is the first row: {matrix[0]}')



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

This is the first row: [0 1 2 3 4]


In [101]:
# 2. Return the last column
matrix = np.arange(0,25).reshape(5,5)
print(matrix)
print(f'\nThis is the last column is: {matrix[:,-1]}')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

This is the last column is: [ 4  9 14 19 24]


In [150]:
# 3. Return the third column values from the 4th and 5th rows
matrix = np.arange(0,25).reshape(5,5)
print(matrix)
print(f'\nThe third column values of 4th row is {matrix[3,2]} and 5th row is {matrix[4,2]}')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The third column values of 4th row is [[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]] and 5th row is 22


In [119]:
# 4. Multiply every value in the array by 2
matrix = np.arange(0,25).reshape(5,5)
print(matrix)
matrix *= 2
print(f'\nMultiplied values by 2\n{matrix}')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Multiplied values by 2
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [231]:
# 5. Divide every value by 3
matrix = np.random.randint(0,100, (5,3)).astype(float)
print(matrix)
matrix /= 3
print(f'\nDivide every value by 3\n{matrix}')

[[80. 14. 32.]
 [17. 86. 64.]
 [99. 95.  1.]
 [85. 42. 17.]
 [94. 49. 52.]]

Divide every value by 3
[[26.66666667  4.66666667 10.66666667]
 [ 5.66666667 28.66666667 21.33333333]
 [33.         31.66666667  0.33333333]
 [28.33333333 14.          5.66666667]
 [31.33333333 16.33333333 17.33333333]]


In [216]:
# 6. Increase the values in the first row by 12
matrix = np.random.randint(0,100, (5,3))
print(matrix)
matrix[0] += 12
print(f'\nAdded top row by 12\n{matrix}')


[[17 72 25]
 [63 81 15]
 [30  7 51]
 [66 78 91]
 [20 23 52]]

Added top row by 12
[[29 84 37]
 [63 81 15]
 [30  7 51]
 [66 78 91]
 [20 23 52]]


In [211]:
# 7. Calculate the mean of the first column
matrix = np.random.randint(0,100, (5,3))
print(matrix)
print(f'\nMean of column 1\n{np.mean(matrix[:,0])}')


[[83 13 51]
 [92 89  3]
 [20 69 58]
 [95 82 59]
 [39 33  9]]

Mean of column 1
65.8


In [310]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
matrix = np.random.randint(0,100, (5,3))
print(matrix)
"""
Going to use https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html
ndarray.flatten(order='C')
to flatten out the matrix, sorted and remove the two numbers.
"""
flattened = matrix.flatten()
flattened.sort()
print(f'\nFlattened and sorted matrix{flattened}')

median = np.median(flattened[2:])
print(f'\nFlattened and removed two lowest: {flattened[2:]}')
print(f'\nMedian after two lowest removed: {median}')


[[80  6 38]
 [24  6 43]
 [57 21 85]
 [36 63 83]
 [ 4 54 34]]

Flattened and sorted matrix[ 4  6  6 21 24 34 36 38 43 54 57 63 80 83 85]

Flattened and removed two lowest: [ 6 21 24 34 36 38 43 54 57 63 80 83 85]

Median after two lowest removed: 43.0


In [289]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array
matrix = np.random.randint(0,100, (5,3))
print(matrix)
      
three_rows = matrix[:3,:]
print(f'\nFirst three rows\n{three_rows}')
std_d = np.std(three_rows)

print(f'\nStandard deviation of the first three rows: {std_d}')

[[40 15 72]
 [22 43 82]
 [75  7 34]
 [49 95 75]
 [85 47 63]]

First three rows
[[40 15 72]
 [22 43 82]
 [75  7 34]]

Standard deviation of the first three rows: 25.81128091014125


In [258]:
# 10. Return values in the second column greater than 25
matrix = np.random.randint(0,100, (5,3))
print(matrix)

two_col = matrix[:,1]
over_25 = two_col[two_col > 25]
print(f'\nValues greater than 25: {over_25}')


[[27 37 57]
 [83 38  8]
 [32 34 10]
 [23 15 87]
 [25 71 92]]

Values greater than 25: [37 38 34 71]


In [270]:
# 11. Return values < 40 in the array
matrix = np.random.randint(0,100, (5,3))
print(matrix)

less_40 = matrix[matrix < 40]
print(f'\nValues less than 40: {less_40}')


[[53 47 60]
 [34 32 19]
 [67 24 83]
 [94 38 47]
 [ 5 79 63]]

Values less than 40: [34 32 19 24 38  5]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [ ]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.5

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])